/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.react.game.core.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.react.game.core.service.model.Ability;
import com.liferay.react.game.core.service.model.AbilityModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Ability service. Represents a row in the &quot;ReactGame_Ability&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AbilityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AbilityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AbilityImpl
 * @generated
 */
public class AbilityModelImpl
	extends BaseModelImpl<Ability> implements AbilityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ability model instance should use the <code>Ability</code> interface instead.
	 */
	public static final String TABLE_NAME = "ReactGame_Ability";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"abilityId", Types.BIGINT},
		{"abilityName", Types.VARCHAR}, {"healing", Types.BOOLEAN},
		{"hitPoints", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("abilityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("abilityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("healing", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hitPoints", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ReactGame_Ability (uuid_ VARCHAR(75) null,abilityId LONG not null primary key,abilityName VARCHAR(75) null,healing BOOLEAN,hitPoints INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ReactGame_Ability";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ability.abilityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ReactGame_Ability.abilityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ABILITYNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ABILITYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AbilityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _abilityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAbilityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _abilityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Ability.class;
	}

	@Override
	public String getModelClassName() {
		return Ability.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Ability, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Ability, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ability, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Ability)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Ability, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Ability, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Ability)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Ability, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Ability, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Ability>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Ability.class.getClassLoader(), Ability.class, ModelWrapper.class);

		try {
			Constructor<Ability> constructor =
				(Constructor<Ability>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Ability, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Ability, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Ability, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Ability, Object>>();
		Map<String, BiConsumer<Ability, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Ability, ?>>();

		attributeGetterFunctions.put("uuid", Ability::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Ability, String>)Ability::setUuid);
		attributeGetterFunctions.put("abilityId", Ability::getAbilityId);
		attributeSetterBiConsumers.put(
			"abilityId", (BiConsumer<Ability, Long>)Ability::setAbilityId);
		attributeGetterFunctions.put("abilityName", Ability::getAbilityName);
		attributeSetterBiConsumers.put(
			"abilityName",
			(BiConsumer<Ability, String>)Ability::setAbilityName);
		attributeGetterFunctions.put("healing", Ability::getHealing);
		attributeSetterBiConsumers.put(
			"healing", (BiConsumer<Ability, Boolean>)Ability::setHealing);
		attributeGetterFunctions.put("hitPoints", Ability::getHitPoints);
		attributeSetterBiConsumers.put(
			"hitPoints", (BiConsumer<Ability, Integer>)Ability::setHitPoints);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAbilityId() {
		return _abilityId;
	}

	@Override
	public void setAbilityId(long abilityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_abilityId = abilityId;
	}

	@Override
	public String getAbilityName() {
		if (_abilityName == null) {
			return "";
		}
		else {
			return _abilityName;
		}
	}

	@Override
	public void setAbilityName(String abilityName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_abilityName = abilityName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAbilityName() {
		return getColumnOriginalValue("abilityName");
	}

	@Override
	public boolean getHealing() {
		return _healing;
	}

	@Override
	public boolean isHealing() {
		return _healing;
	}

	@Override
	public void setHealing(boolean healing) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_healing = healing;
	}

	@Override
	public int getHitPoints() {
		return _hitPoints;
	}

	@Override
	public void setHitPoints(int hitPoints) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hitPoints = hitPoints;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Ability.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Ability toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Ability>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AbilityImpl abilityImpl = new AbilityImpl();

		abilityImpl.setUuid(getUuid());
		abilityImpl.setAbilityId(getAbilityId());
		abilityImpl.setAbilityName(getAbilityName());
		abilityImpl.setHealing(isHealing());
		abilityImpl.setHitPoints(getHitPoints());

		abilityImpl.resetOriginalValues();

		return abilityImpl;
	}

	@Override
	public Ability cloneWithOriginalValues() {
		AbilityImpl abilityImpl = new AbilityImpl();

		abilityImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		abilityImpl.setAbilityId(
			this.<Long>getColumnOriginalValue("abilityId"));
		abilityImpl.setAbilityName(
			this.<String>getColumnOriginalValue("abilityName"));
		abilityImpl.setHealing(this.<Boolean>getColumnOriginalValue("healing"));
		abilityImpl.setHitPoints(
			this.<Integer>getColumnOriginalValue("hitPoints"));

		return abilityImpl;
	}

	@Override
	public int compareTo(Ability ability) {
		long primaryKey = ability.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Ability)) {
			return false;
		}

		Ability ability = (Ability)object;

		long primaryKey = ability.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Ability> toCacheModel() {
		AbilityCacheModel abilityCacheModel = new AbilityCacheModel();

		abilityCacheModel.uuid = getUuid();

		String uuid = abilityCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			abilityCacheModel.uuid = null;
		}

		abilityCacheModel.abilityId = getAbilityId();

		abilityCacheModel.abilityName = getAbilityName();

		String abilityName = abilityCacheModel.abilityName;

		if ((abilityName != null) && (abilityName.length() == 0)) {
			abilityCacheModel.abilityName = null;
		}

		abilityCacheModel.healing = isHealing();

		abilityCacheModel.hitPoints = getHitPoints();

		return abilityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Ability, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Ability, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ability, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Ability)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Ability, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Ability, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ability, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Ability)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Ability>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _abilityId;
	private String _abilityName;
	private boolean _healing;
	private int _hitPoints;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Ability, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Ability)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("abilityId", _abilityId);
		_columnOriginalValues.put("abilityName", _abilityName);
		_columnOriginalValues.put("healing", _healing);
		_columnOriginalValues.put("hitPoints", _hitPoints);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("abilityId", 2L);

		columnBitmasks.put("abilityName", 4L);

		columnBitmasks.put("healing", 8L);

		columnBitmasks.put("hitPoints", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Ability _escapedModel;

}