/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.react.game.core.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.react.game.core.service.model.PlayerEnemyAbility;
import com.liferay.react.game.core.service.model.PlayerEnemyAbilityModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PlayerEnemyAbility service. Represents a row in the &quot;ReactGame_PlayerEnemyAbility&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PlayerEnemyAbilityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlayerEnemyAbilityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlayerEnemyAbilityImpl
 * @generated
 */
public class PlayerEnemyAbilityModelImpl
	extends BaseModelImpl<PlayerEnemyAbility>
	implements PlayerEnemyAbilityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a player enemy ability model instance should use the <code>PlayerEnemyAbility</code> interface instead.
	 */
	public static final String TABLE_NAME = "ReactGame_PlayerEnemyAbility";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"playerEnemyAbilityId", Types.BIGINT},
		{"enemy", Types.BOOLEAN}, {"playerOrEnemyId", Types.BIGINT},
		{"abilityId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("playerEnemyAbilityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("enemy", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("playerOrEnemyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("abilityId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ReactGame_PlayerEnemyAbility (uuid_ VARCHAR(75) null,playerEnemyAbilityId LONG not null primary key,enemy BOOLEAN,playerOrEnemyId LONG,abilityId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ReactGame_PlayerEnemyAbility";

	public static final String ORDER_BY_JPQL =
		" ORDER BY playerEnemyAbility.playerEnemyAbilityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ReactGame_PlayerEnemyAbility.playerEnemyAbilityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLAYERORENEMYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLAYERENEMYABILITYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PlayerEnemyAbilityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _playerEnemyAbilityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPlayerEnemyAbilityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _playerEnemyAbilityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PlayerEnemyAbility.class;
	}

	@Override
	public String getModelClassName() {
		return PlayerEnemyAbility.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PlayerEnemyAbility, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PlayerEnemyAbility, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlayerEnemyAbility, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PlayerEnemyAbility)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PlayerEnemyAbility, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PlayerEnemyAbility, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PlayerEnemyAbility)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PlayerEnemyAbility, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PlayerEnemyAbility, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PlayerEnemyAbility>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PlayerEnemyAbility.class.getClassLoader(), PlayerEnemyAbility.class,
			ModelWrapper.class);

		try {
			Constructor<PlayerEnemyAbility> constructor =
				(Constructor<PlayerEnemyAbility>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PlayerEnemyAbility, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PlayerEnemyAbility, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PlayerEnemyAbility, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PlayerEnemyAbility, Object>>();
		Map<String, BiConsumer<PlayerEnemyAbility, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PlayerEnemyAbility, ?>>();

		attributeGetterFunctions.put("uuid", PlayerEnemyAbility::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PlayerEnemyAbility, String>)
				PlayerEnemyAbility::setUuid);
		attributeGetterFunctions.put(
			"playerEnemyAbilityId",
			PlayerEnemyAbility::getPlayerEnemyAbilityId);
		attributeSetterBiConsumers.put(
			"playerEnemyAbilityId",
			(BiConsumer<PlayerEnemyAbility, Long>)
				PlayerEnemyAbility::setPlayerEnemyAbilityId);
		attributeGetterFunctions.put("enemy", PlayerEnemyAbility::getEnemy);
		attributeSetterBiConsumers.put(
			"enemy",
			(BiConsumer<PlayerEnemyAbility, Boolean>)
				PlayerEnemyAbility::setEnemy);
		attributeGetterFunctions.put(
			"playerOrEnemyId", PlayerEnemyAbility::getPlayerOrEnemyId);
		attributeSetterBiConsumers.put(
			"playerOrEnemyId",
			(BiConsumer<PlayerEnemyAbility, Long>)
				PlayerEnemyAbility::setPlayerOrEnemyId);
		attributeGetterFunctions.put(
			"abilityId", PlayerEnemyAbility::getAbilityId);
		attributeSetterBiConsumers.put(
			"abilityId",
			(BiConsumer<PlayerEnemyAbility, Long>)
				PlayerEnemyAbility::setAbilityId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getPlayerEnemyAbilityId() {
		return _playerEnemyAbilityId;
	}

	@Override
	public void setPlayerEnemyAbilityId(long playerEnemyAbilityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playerEnemyAbilityId = playerEnemyAbilityId;
	}

	@Override
	public boolean getEnemy() {
		return _enemy;
	}

	@Override
	public boolean isEnemy() {
		return _enemy;
	}

	@Override
	public void setEnemy(boolean enemy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_enemy = enemy;
	}

	@Override
	public long getPlayerOrEnemyId() {
		return _playerOrEnemyId;
	}

	@Override
	public void setPlayerOrEnemyId(long playerOrEnemyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playerOrEnemyId = playerOrEnemyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlayerOrEnemyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("playerOrEnemyId"));
	}

	@Override
	public long getAbilityId() {
		return _abilityId;
	}

	@Override
	public void setAbilityId(long abilityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_abilityId = abilityId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PlayerEnemyAbility.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PlayerEnemyAbility toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PlayerEnemyAbility>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PlayerEnemyAbilityImpl playerEnemyAbilityImpl =
			new PlayerEnemyAbilityImpl();

		playerEnemyAbilityImpl.setUuid(getUuid());
		playerEnemyAbilityImpl.setPlayerEnemyAbilityId(
			getPlayerEnemyAbilityId());
		playerEnemyAbilityImpl.setEnemy(isEnemy());
		playerEnemyAbilityImpl.setPlayerOrEnemyId(getPlayerOrEnemyId());
		playerEnemyAbilityImpl.setAbilityId(getAbilityId());

		playerEnemyAbilityImpl.resetOriginalValues();

		return playerEnemyAbilityImpl;
	}

	@Override
	public PlayerEnemyAbility cloneWithOriginalValues() {
		PlayerEnemyAbilityImpl playerEnemyAbilityImpl =
			new PlayerEnemyAbilityImpl();

		playerEnemyAbilityImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		playerEnemyAbilityImpl.setPlayerEnemyAbilityId(
			this.<Long>getColumnOriginalValue("playerEnemyAbilityId"));
		playerEnemyAbilityImpl.setEnemy(
			this.<Boolean>getColumnOriginalValue("enemy"));
		playerEnemyAbilityImpl.setPlayerOrEnemyId(
			this.<Long>getColumnOriginalValue("playerOrEnemyId"));
		playerEnemyAbilityImpl.setAbilityId(
			this.<Long>getColumnOriginalValue("abilityId"));

		return playerEnemyAbilityImpl;
	}

	@Override
	public int compareTo(PlayerEnemyAbility playerEnemyAbility) {
		long primaryKey = playerEnemyAbility.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PlayerEnemyAbility)) {
			return false;
		}

		PlayerEnemyAbility playerEnemyAbility = (PlayerEnemyAbility)object;

		long primaryKey = playerEnemyAbility.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PlayerEnemyAbility> toCacheModel() {
		PlayerEnemyAbilityCacheModel playerEnemyAbilityCacheModel =
			new PlayerEnemyAbilityCacheModel();

		playerEnemyAbilityCacheModel.uuid = getUuid();

		String uuid = playerEnemyAbilityCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			playerEnemyAbilityCacheModel.uuid = null;
		}

		playerEnemyAbilityCacheModel.playerEnemyAbilityId =
			getPlayerEnemyAbilityId();

		playerEnemyAbilityCacheModel.enemy = isEnemy();

		playerEnemyAbilityCacheModel.playerOrEnemyId = getPlayerOrEnemyId();

		playerEnemyAbilityCacheModel.abilityId = getAbilityId();

		return playerEnemyAbilityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PlayerEnemyAbility, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PlayerEnemyAbility, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlayerEnemyAbility, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PlayerEnemyAbility)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PlayerEnemyAbility, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PlayerEnemyAbility, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlayerEnemyAbility, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PlayerEnemyAbility)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PlayerEnemyAbility>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _playerEnemyAbilityId;
	private boolean _enemy;
	private long _playerOrEnemyId;
	private long _abilityId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PlayerEnemyAbility, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PlayerEnemyAbility)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"playerEnemyAbilityId", _playerEnemyAbilityId);
		_columnOriginalValues.put("enemy", _enemy);
		_columnOriginalValues.put("playerOrEnemyId", _playerOrEnemyId);
		_columnOriginalValues.put("abilityId", _abilityId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("playerEnemyAbilityId", 2L);

		columnBitmasks.put("enemy", 4L);

		columnBitmasks.put("playerOrEnemyId", 8L);

		columnBitmasks.put("abilityId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PlayerEnemyAbility _escapedModel;

}