/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.react.game.core.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.react.game.core.service.model.Player;
import com.liferay.react.game.core.service.model.PlayerModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Player service. Represents a row in the &quot;ReactGame_Player&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PlayerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlayerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlayerImpl
 * @generated
 */
public class PlayerModelImpl
	extends BaseModelImpl<Player> implements PlayerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a player model instance should use the <code>Player</code> interface instead.
	 */
	public static final String TABLE_NAME = "ReactGame_Player";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"playerId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"playerName", Types.VARCHAR},
		{"level", Types.INTEGER}, {"xpPoints", Types.INTEGER},
		{"hitPoints", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("playerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("playerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("level", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("xpPoints", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("hitPoints", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ReactGame_Player (uuid_ VARCHAR(75) null,playerId LONG not null primary key,userId LONG,playerName VARCHAR(75) null,level INTEGER,xpPoints INTEGER,hitPoints INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ReactGame_Player";

	public static final String ORDER_BY_JPQL = " ORDER BY player.playerId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ReactGame_Player.playerId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLAYERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PlayerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _playerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPlayerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _playerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Player.class;
	}

	@Override
	public String getModelClassName() {
		return Player.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Player, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Player, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Player, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Player)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Player, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Player, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Player)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Player, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Player, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Player>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Player.class.getClassLoader(), Player.class, ModelWrapper.class);

		try {
			Constructor<Player> constructor =
				(Constructor<Player>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Player, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Player, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Player, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Player, Object>>();
		Map<String, BiConsumer<Player, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Player, ?>>();

		attributeGetterFunctions.put("uuid", Player::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Player, String>)Player::setUuid);
		attributeGetterFunctions.put("playerId", Player::getPlayerId);
		attributeSetterBiConsumers.put(
			"playerId", (BiConsumer<Player, Long>)Player::setPlayerId);
		attributeGetterFunctions.put("userId", Player::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Player, Long>)Player::setUserId);
		attributeGetterFunctions.put("playerName", Player::getPlayerName);
		attributeSetterBiConsumers.put(
			"playerName", (BiConsumer<Player, String>)Player::setPlayerName);
		attributeGetterFunctions.put("level", Player::getLevel);
		attributeSetterBiConsumers.put(
			"level", (BiConsumer<Player, Integer>)Player::setLevel);
		attributeGetterFunctions.put("xpPoints", Player::getXpPoints);
		attributeSetterBiConsumers.put(
			"xpPoints", (BiConsumer<Player, Integer>)Player::setXpPoints);
		attributeGetterFunctions.put("hitPoints", Player::getHitPoints);
		attributeSetterBiConsumers.put(
			"hitPoints", (BiConsumer<Player, Integer>)Player::setHitPoints);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getPlayerId() {
		return _playerId;
	}

	@Override
	public void setPlayerId(long playerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playerId = playerId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getPlayerName() {
		if (_playerName == null) {
			return "";
		}
		else {
			return _playerName;
		}
	}

	@Override
	public void setPlayerName(String playerName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playerName = playerName;
	}

	@Override
	public int getLevel() {
		return _level;
	}

	@Override
	public void setLevel(int level) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_level = level;
	}

	@Override
	public int getXpPoints() {
		return _xpPoints;
	}

	@Override
	public void setXpPoints(int xpPoints) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_xpPoints = xpPoints;
	}

	@Override
	public int getHitPoints() {
		return _hitPoints;
	}

	@Override
	public void setHitPoints(int hitPoints) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hitPoints = hitPoints;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Player.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Player toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Player>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PlayerImpl playerImpl = new PlayerImpl();

		playerImpl.setUuid(getUuid());
		playerImpl.setPlayerId(getPlayerId());
		playerImpl.setUserId(getUserId());
		playerImpl.setPlayerName(getPlayerName());
		playerImpl.setLevel(getLevel());
		playerImpl.setXpPoints(getXpPoints());
		playerImpl.setHitPoints(getHitPoints());

		playerImpl.resetOriginalValues();

		return playerImpl;
	}

	@Override
	public Player cloneWithOriginalValues() {
		PlayerImpl playerImpl = new PlayerImpl();

		playerImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		playerImpl.setPlayerId(this.<Long>getColumnOriginalValue("playerId"));
		playerImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		playerImpl.setPlayerName(
			this.<String>getColumnOriginalValue("playerName"));
		playerImpl.setLevel(this.<Integer>getColumnOriginalValue("level"));
		playerImpl.setXpPoints(
			this.<Integer>getColumnOriginalValue("xpPoints"));
		playerImpl.setHitPoints(
			this.<Integer>getColumnOriginalValue("hitPoints"));

		return playerImpl;
	}

	@Override
	public int compareTo(Player player) {
		long primaryKey = player.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Player)) {
			return false;
		}

		Player player = (Player)object;

		long primaryKey = player.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Player> toCacheModel() {
		PlayerCacheModel playerCacheModel = new PlayerCacheModel();

		playerCacheModel.uuid = getUuid();

		String uuid = playerCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			playerCacheModel.uuid = null;
		}

		playerCacheModel.playerId = getPlayerId();

		playerCacheModel.userId = getUserId();

		playerCacheModel.playerName = getPlayerName();

		String playerName = playerCacheModel.playerName;

		if ((playerName != null) && (playerName.length() == 0)) {
			playerCacheModel.playerName = null;
		}

		playerCacheModel.level = getLevel();

		playerCacheModel.xpPoints = getXpPoints();

		playerCacheModel.hitPoints = getHitPoints();

		return playerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Player, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Player, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Player, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Player)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Player, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Player, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Player, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Player)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Player>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _playerId;
	private long _userId;
	private String _playerName;
	private int _level;
	private int _xpPoints;
	private int _hitPoints;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Player, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Player)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("playerId", _playerId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("playerName", _playerName);
		_columnOriginalValues.put("level", _level);
		_columnOriginalValues.put("xpPoints", _xpPoints);
		_columnOriginalValues.put("hitPoints", _hitPoints);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("playerId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("playerName", 8L);

		columnBitmasks.put("level", 16L);

		columnBitmasks.put("xpPoints", 32L);

		columnBitmasks.put("hitPoints", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Player _escapedModel;

}